from enum import Enum
class MarketDataField(Enum):
    NoMDEntries=1
    OpeningPrice=2
    ClosingPrice=3
    SettlementPrice=4
    TradingSessionHighPrice=5
    TradingSessionLowPrice=6
    TradingSessionVWAPPrice=7
    Imbalance=8
    TradeVolume=9
    OpenInterest=10
    CompositeUnderlyingPrice=11
    MarginRate=12
    MidPrice=13
    SettleHighPrice=14
    SettlPriorPrice=15
    SessionHighBid=16
    SessionLowOffer=17
    EarlyPrices=18
    AuctionClearingPrice=19
    Trade=20
    MDUpdateAction=21
    Currency=22
    MDEntryDate=23
    MDEntryTime=24
    TickDirection=25
    SettlType=26
    SettlDate=27
    Symbol=28
    SecurityType=29
    MDMkt=30
    BestBidPrice=31
    BestAskPrice=32
    BestAskSize=33
    BestBidSize=34
    BestAskExch=35
    BestBidExch=36
    MDTradeSize=37
    MDLocalEntryDate=38
    ReverseMarketData=39
    BestBidCashSize=40
    BestAskCashSize=41
    LastTradeDateTime=42
    Change = 43
    StdDev = 44